# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BdikaSDKExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'BdikaSDK', :path => '../BdikaSDK.podspec'
  
  target 'BdikaSDKExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BdikaSDKExampleUITests' do
    # Pods for testing
  end

end
